create optional interface
develhope/Java23-Team2-Dealer pull request #15
Opened 2024-05-17 17:52 UTC by gabrielD4

2024-05-17 17:59 UTC, ilGrandeWorro requested changes

2024-05-17 17:59 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/model/vehicle/optionals/Optionals.java
> +import java.math.BigDecimal;
Questo non viene utilizzato all'interno di questa interfaccia. Lorenzo ci fece togliere le classi importate che non vengono utilizzate nello scorso progetto

2024-05-18 08:33 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/model/vehicle/optionals/Optionals.java
> +import java.math.BigDecimal;
hai ragione è rimasto l'import dal precedente tentativo di far funzionare il metodo come dicevamo. Occhio attento.

2024-05-18 08:56 UTC, ilGrandeWorro approved these changes

2024-05-19 20:02 UTC, merged