Air Conditioner optional
develhope/Java23-Team2-Dealer pull request #23
Opened 2024-05-21 00:25 UTC by ilGrandeWorro

Created AirConditioner entity, moved Optionals from its former and obsolete package to the new one, also moved TractionControl

2024-05-21 09:36 UTC, gabrielD4 requested changes

2024-05-21 09:36 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/vehicle/optionals/models/AirConditioner.java
> +    public long getId() {
manca il set di Id, getter e setter vanno normalmente messi a meno che non ci sia qualche logica particolare, per i motivi spiegati sempre nella request #22

2024-05-21 09:36 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/vehicle/optionals/models/Optionals.java
> +package com.develhope.spring.vehicle.optionals.models;
mh occhio a questo e gli altri repack. Già lo avevo fatto io nella mia pull request e diversamente,  potrebbe creare conflitti forse farai un revert di questa cosa dato che è già stato fatto.

2024-05-22 10:36 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/vehicle/optionals/models/Optionals.java
> +package com.develhope.spring.vehicle.optionals.models;
Lo so, ma la tua pull non è ancora stata mergiata, quindi ci sarà comunque da fare un repackaging alla fine

2024-05-22 10:43 UTC, gabrielD4 requested changes

2024-05-22 10:43 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/vehicle/optionals/models/Optionals.java
> +package com.develhope.spring.vehicle.optionals.models;
ora è stata mergiata, difatti ti da qualche conflitto. Aggiusta eventuali conflitti ed allinea i package e siamo apposto.

2024-05-22 11:16 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/vehicle/optionals/models/Optionals.java
> +package com.develhope.spring.vehicle.optionals.models;
Dovrebbe essere ok

2024-05-22 11:48 UTC, OigreSergio approved these changes

2024-05-22 12:13 UTC, Calyen93 approved these changes
Segna risolti gli altri conflitti

2024-05-22 14:13 UTC, merged