Vehicle class
develhope/Java23-Team2-Dealer pull request #3
Opened 2024-05-10 15:55 UTC by ilGrandeWorro

I'd focus on the optionals system. It's a package of objects and its builders that will be implemented in the vehicle object as variables, every optional must be initialized and setted when you want to add it at the final product

2024-05-11 11:52 UTC, OigreSergio approved these changes

2024-05-13 08:27 UTC, gabrielD4 commented
mi sento male all'idea di dover guardare tutta sta pull request

2024-05-13 08:37 UTC, alegudev39 commented on src/main/java/vehicle/Vehicle.java
in revisione. Bene composizione a partire da variabili

2024-05-13 08:49 UTC, Calyen93 requested changes
rinomina tutti i getter con getNomeMetodo al posto di isNomeMetodo

2024-05-13 08:49 UTC, Calyen93 commented on src/main/java/vehicle/optionals/wheels/WheelsBuilder.java
isAlloyWheels e IsAllWhellDrives sono Getter, chiamali getAlloyWheels getAllWhellDrivers

2024-05-13 08:49 UTC, Calyen93 commented on src/main/java/vehicle/optionals/windows/WindowsBuilder.java
isHeatedWindows e isTintedWindows sono due getter, chiamali getHeatedWindows e getTintedWindows

2024-05-13 08:52 UTC, Calyen93 commented on src/main/java/vehicle/optionals/informatic/Informatic.java
chiama i getter non con is ma con get

2024-05-13 08:58 UTC, Calyen93 requested changes

2024-05-13 08:58 UTC, Calyen93 commented on src/main/java/vehicle/optionals/seats/SeatsBuilder.java
chiama i getter non con is ma con get

2024-05-13 08:58 UTC, Calyen93 commented on src/main/java/vehicle/optionals/doors/DoorsBuilder.java
chiama i getter non con is ma con get

2024-05-13 10:30 UTC, ilGrandeWorro commented on src/main/java/vehicle/optionals/wheels/WheelsBuilder.java
I getter dei booleani me li ha generati in automatico con is invece che get

2024-05-13 16:02 UTC, gabrielD4 requested changes

2024-05-13 16:02 UTC, gabrielD4 commented on src/main/java/vehicle/VehicleBuilder.java
> +    public VehicleBuilder(String brand, String model, double originalPrice, int id) {
scusami ale, era corretto static ora che ci penso. Se non lo metti static non possiamo usare il builder fino a che un person non è creato.

2024-05-13 17:20 UTC, ilGrandeWorro commented on src/main/java/vehicle/VehicleBuilder.java
> +    public VehicleBuilder(String brand, String model, double originalPrice, int id) {
Sì, l'ho notato perché altrimenti non mi funzionava nel test. L'ho lasciato static

2024-05-13 17:53 UTC, gabrielD4 commented on src/main/java/vehicle/VehicleBuilder.java
> +    public VehicleBuilder(String brand, String model, double originalPrice, int id) {
allora ripushalo poi quando puoi così megiamo

2024-05-13 18:01 UTC, gabrielD4 commented on src/main/java/vehicle/VehicleBuilder.java
> +    public VehicleBuilder(String brand, String model, double originalPrice, int id) {
mi rendo conto ora di aver commentato la riga sbagliata

2024-05-13 18:02 UTC, gabrielD4 approved these changes

2024-05-13 18:21 UTC, Calyen93 approved these changes

2024-05-13 22:24 UTC, merged