Modify Vehicle method
develhope/Java23-Team2-Dealer pull request #31
Opened 2024-05-24 11:33 UTC by Calyen93

aggiunto metodo che permetta la modifica dei valori dei veicoli all'admin

2024-05-24 16:35 UTC, gabrielD4 requested changes

2024-05-24 16:35 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/vehicle/controller/VehicleController.java
> +@RequestMapping("/api/vehicle")
ecco accordiamoci su sta cosa. Io userei il sistema di version anche se inutile. Quindi partirei defininedo l 'url con /v1 al posto di /api. Per convenzione mi pare che lorenzo disse inoltre che devono essere al plurale le entità del path. Quindi dovrebbe essere vehicles se mal non ricordo.

2024-05-24 16:35 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/vehicle/service/VehicleService.java
> +    public void deleteVehicle(long id) {
Devi assicurarti che solo l'admin possa fare questa operazione.  Quindi devi o passargli uno user da cui prendi il ruolo e verifichi che sia un admin. O un id utente e ugualmente tramite id trovi lo user e verifichi che abbia il ruolo di admin prima di procedere con l'operazione. Inoltre devi controllare il caso in cui tramite id non trovi nulla. Sia se non trovi un utente, sia se non trovi un veicolo. Altrimenti il programma da un 500 internal server error. Quindi devi lanciare le eccezioni qua, e nel controller tramite exception handler come ha fatto vedere Lorenzo nel pomeriggio, le vai a gestire.

2024-05-24 16:35 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/vehicle/controller/VehicleController.java
> +    @DeleteMapping("/{id}")
Tutto il controller di conseguenza cambia in funzione di ciò che è stato scritto nel service

2024-05-27 13:29 UTC, OigreSergio approved these changes

2024-05-28 13:38 UTC, closed without merging