Allow Wheels model created
develhope/Java23-Team2-Dealer pull request #32
Opened 2024-05-24 14:07 UTC by OigreSergio

I made the Allow Wheels Entity into vehicle/optional/models

2024-05-24 16:40 UTC, gabrielD4 requested changes

2024-05-24 16:40 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/vehicle/optionals/models/AllowWheels.java
> +    @GeneratedValue
Aggiungerei tra parentesi (strategy = GenerationType.IDENTITY)

2024-05-24 16:40 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/vehicle/optionals/models/AllowWheels.java
> +    public long getId() {
Mancano diversi getter e setter

2024-05-24 16:40 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/vehicle/optionals/models/AllowWheels.java
> +public class AllowWheels {
Ok guardando meglio ho scoperto che il nome corretto della classe dovrebbe essere Rim che vuol dire cerchioni. Mentre alloyWheels vuol dire proprio cerchi in lega

2024-05-24 16:40 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/vehicle/optionals/models/AllowWheels.java
> +    private boolean ilLega;
Questa dovrebbe chiamarsi alloyWheels

2024-05-28 11:36 UTC, ilGrandeWorro requested changes

2024-05-28 11:36 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/vehicle/optionals/models/AllowWheels.java
> +    private boolean chromiumPlated;
Perché usiamo i boolean invece che gli enum qui?

2024-05-28 11:36 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/vehicle/optionals/models/AllowWheels.java
> +    private boolean colored;
manca il price

2024-05-29 22:13 UTC, closed without merging