Modify vehicle Endpoint
develhope/Java23-Team2-Dealer pull request #37
Opened 2024-05-28 16:46 UTC by Calyen93

2024-05-29 09:36 UTC, ilGrandeWorro requested changes

2024-05-29 09:36 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/vehicles/services/VehicleService.java
> +        Vehicle vehicle = optionalVehicle.get();
Tutta questa sequenza di setter e getter non è necessaria se usi il RequestBody sul controller. L'unica cosa che controllerei è che l'ID rimanga lo stesso nonostante il cambio del resto del body. 
suggerirei quindi:

updatedVehicle.setId(vehicleId)
return vehicleRepository.save(updatedVehcile)

2024-05-29 10:30 UTC, gabrielD4 requested changes

2024-05-29 12:12 UTC, gabrielD4 commented
Non vedo modifiche o commenti riguardo le review. Rimetto in doing

2024-05-29 12:15 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/vehicles/models/exceptions/VehicleNotFoundException.java
> +@ResponseStatus(HttpStatus.NOT_FOUND)
hai risolto ma non hai modificato ne commentato al riguardo

2024-05-29 15:18 UTC, gabrielD4 requested changes

2024-05-29 15:18 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/vehicles/services/VehicleService.java
> +    public VehicleDTO create(long userId, Vehicle vehicleDTO) {
bravo che hai cambiato anche questo metodo

2024-05-29 15:18 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/vehicles/models/Vehicle.java
> +    public boolean getOrderable() {
vanno rimossi

2024-05-29 15:18 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/vehicles/dto/VehicleDTO.java
> +public class VehicleDTO {
Va nominato con la sua funzione come diceva Lorenzo. Quindi roba tipo VehicleCreateDto o VehicleUpdateDto o boh qualcosa che abbia un senso comunque

2024-05-29 15:18 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/vehicles/controllers/VehicleController.java
> +    public VehicleDTO update(@PathVariable long userId, @PathVariable long vehicleId, @RequestBody Vehicle vehicle) {
Occhio che stai passando vehicle e non il DTO

2024-05-29 15:18 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/vehicles/controllers/VehicleController.java
> +    public ResponseEntity<VehicleDTO> create(@PathVariable long userId, @RequestBody Vehicle vehicle) {
stai passando Vehicle e non il DTO

2024-05-29 15:56 UTC, gabrielD4 requested changes

2024-05-29 15:56 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/vehicles/dto/VehicleDTO.java
> +package com.develhope.spring.vehicles.dto;
metterei il package al plurale quindi dtos

2024-05-31 09:01 UTC, alegudev39 commented on src/main/java/com/develhope/spring/deals/models/Order.java
>      private boolean downPayment;
è come un isPaid? cioè rappresenta se il pagamento è completato o no?

2024-05-31 09:02 UTC, alegudev39 commented on src/main/java/com/develhope/spring/vehicles/configuration/ModelMapperConfig.java
basta un bean per più istanze?

2024-05-31 09:05 UTC, alegudev39 approved these changes
bel lavoro!

2024-05-31 09:57 UTC, ilGrandeWorro requested changes

2024-05-31 09:57 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/deals/models/Order.java
>      private boolean downPayment;
è l'anticipo

2024-05-31 09:57 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/deals/models/Order.java
> +    public Vehicle getVehicleId() {
Cambiare il nome del getter

2024-05-31 09:57 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/deals/models/Order.java
>      public void setVehicleId(int vehicleId) {
E cambiare il nome del setter (ovviamente)

2024-05-31 09:57 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/deals/models/Order.java
> +                ", Id del veicolo = " + vehicle +
anche qui da fare la modifica, anche se non credo ci serva il toString, quindi lo rimuoverei direttamente

2024-05-31 09:57 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/vehicles/dtos/VehicleCreateDTO.java
> +    private Long id;
L'id si può rimuovere, visto che è autogenerato

2024-05-31 09:57 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/vehicles/models/Vehicle.java
> +    public Vehicle(long id) {
Perché un costruttore con solo l'ID?

2024-05-31 09:57 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/vehicles/models/Vehicle.java
> +    /**
Ma è all'interno della classe Vehicle, mettilo in una classe a parte

2024-05-31 09:57 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/vehicles/models/exceptions/VehicleNotFoundException.java
> -
Perché è stato rimosso?

2024-05-31 09:57 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/vehicles/services/VehicleService.java
> +            throw new UserNotFoundException("Nessun utente con questo ID: " + userId + " è presente");
Perché traduzione inglese -> italiano?

2024-05-31 14:49 UTC, gabrielD4 requested changes

2024-05-31 14:49 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/vehicles/dtos/VehicleCreateDTO.java
> +    private Long id;
non ci deve stare l' id

2024-05-31 15:47 UTC, gabrielD4 approved these changes

2024-05-31 15:48 UTC, merged