New branch
develhope/Java23-Team2-Dealer pull request #4
Opened 2024-05-11 09:39 UTC by OigreSergio

2024-05-11 11:06 UTC, ilGrandeWorro requested changes

2024-05-11 11:06 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/Metods/Users.java
> +package com.develhope.spring.Metods;
Methods andrebbe dentro il package users

2024-05-11 11:30 UTC, ilGrandeWorro commented on src/main/java/com/.DS_Store
Non ho idea di cosa sia

2024-05-12 19:29 UTC, ilGrandeWorro requested changes

2024-05-12 19:29 UTC, ilGrandeWorro commented on src/main/java/com/.DS_Store
Spostialo in Gitignore e poi rinomina il branch, per  il resto ci siamo

2024-05-13 08:25 UTC, gabrielD4 requested changes

2024-05-13 08:25 UTC, gabrielD4 commented on src/main/java/User/Methods/Methods.java
> +package User.Methods;
non comprendo l'utilità di questo package con dentro una sola classe. Questi sono i ruoli dello user, dovrebbero stare nel package user. Il package serve in teoria se vanno raggruppate più cose, non per una sola classe

2024-05-13 08:25 UTC, gabrielD4 commented on src/main/java/User/Methods/Methods.java
> +public enum Methods {
Forse mi sono perso qualcsoa nel weekend, perchè è chiamata methods? Sono ruoli

2024-05-13 08:25 UTC, gabrielD4 commented on src/main/java/User/SegnapostoUser.java
> +public class SegnapostoUser {
Cos'è questa classe?

2024-05-13 10:25 UTC, gabrielD4 requested changes

2024-05-13 10:25 UTC, gabrielD4 commented on src/main/java/User/Roles.java
> +package User;
user minuscolo e il package va dentro models

2024-05-13 15:29 UTC, merged