Create User
develhope/Java23-Team2-Dealer pull request #40
Opened 2024-05-29 13:45 UTC by ilGrandeWorro

2024-05-29 14:24 UTC, Calyen93 commented on src/main/java/com/develhope/spring/users/controllers/UserController.java
usa @ResponseStatus(HttpStatus.ACCEPTED)

2024-05-29 15:45 UTC, gabrielD4 requested changes

2024-05-29 15:45 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/users/controllers/UserController.java
> +    @PostMapping("/registration")
gli url dovrebbero essere i più brevi possibili ed essenziali. Direi che è superfluo registration. Normalmente nelle post non aggiungiamo null'altro che l'url base.

2024-05-29 15:45 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/users/controllers/UserController.java
> +    public ResponseEntity<User> registrateUser(@RequestBody User user){
Come suggerito a Claudio avendo una sola risposta puoi risparmiare codice usando l'annotazione @ResposneStatus sopra il metodo e fra parentesi specificargli Httpstatus.Created ed evitare la ResponseEntity

2024-05-29 15:47 UTC, gabrielD4 requested changes

2024-05-29 15:47 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/users/services/UserService.java
> +    public User createUser (User user){
Creerei un DTO per la creazione dello user, che specifichi nel nome la sua funzione. Ad esempio UserCreatorDTO

2024-05-31 11:19 UTC, gabrielD4 requested changes

2024-05-31 11:19 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/users/controllers/UserController.java
> +    private UserRepository userRepository;
Questa assolutamente non dovrebbe stare qua xD

2024-05-31 11:19 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/users/dto/UserCreationDTO.java
> +    public UserCreationDTO() {
Vi ricordo sempre che le classi devono essere un sostantivo. Quindi sarebbe meglio quindi UserCreatorDTO

2024-05-31 11:19 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/users/components/Mapper.java
> +    public User toUser(UserCreationDTO userDTO) {
lo rinominerei toEntity per chiarezza. Però buona la cosa del component

2024-05-31 16:07 UTC, gabrielD4 requested changes

2024-05-31 16:07 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/users/components/Mapper.java
> +    public User toUser(UserCreationDTO userDTO) {
Reimposta il mapper seguendo la guida ed anche il riferimento di codice che già trovi nel progetto mergiato da claudio

2024-05-31 16:10 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/users/controllers/UserController.java
> +    private UserRepository userRepository;
![43526bdfb7907cab422155b9b9e4db6c](https://github.com/develhope/Java23-Team2-Dealer/assets/158162692/f42cfba6-d7bd-4959-aa10-e964f270e357)

La mia espressione quando l'ho visto

2024-06-03 12:14 UTC, gabrielD4 requested changes

2024-06-03 15:57 UTC, gabrielD4 requested changes

2024-06-03 15:57 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/users/components/UserMapper.java
> +    public UserSavedDTO fromEntityToUserSavedDTO(User user) {
CI standardiziamo sul chiamare questi metodi con to*DTODiDestinazione*From(Class<T> class)

2024-06-03 15:57 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/users/controllers/UserController.java
> +    private UserMapper userMapper;
Questo non dovrebbe stare qua

2024-06-03 15:57 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/users/services/UserService.java
> +        return userMapper.fromEntityToUserSavedDTO(userRepository.save(userMapper.fromUserCreatorDTOtoEntity(userCreatorDTO)));
in questo caso creare una variabile rende più facile la lettura

2024-06-03 16:29 UTC, gabrielD4 approved these changes

2024-06-03 16:29 UTC, merged