Fix problem on alloy wheels
develhope/Java23-Team2-Dealer pull request #45
Opened 2024-06-03 08:40 UTC by OigreSergio

I just fix the problems

2024-06-03 11:19 UTC, ilGrandeWorro requested changes

2024-06-03 11:19 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/vehicles/optionals/enums/TypeOfRim.java
> +    AlloyWheels;
da riscrivere in capslock

2024-06-03 11:19 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/vehicles/optionals/models/AlloyWheels.java
> +    private TypeOfRim type;
il nome rendilo uguale al tipo (ovviamente in camel case)

2024-06-03 11:19 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/vehicles/optionals/models/AlloyWheels.java
> +        this.price = price;
aggiungere .setScale(2, RoundingMode.HALF_EVEN);

2024-06-03 11:19 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/vehicles/optionals/models/AlloyWheels.java
> +        this.price = price;
anche qui aggiungere .setScale(2, RoundingMode.HALF_EVEN);

2024-06-03 11:19 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/vehicles/optionals/models/AlloyWheels.java
Aggiungere setter e getter di type e inserirlo nel costruttore

2024-06-03 15:14 UTC, ilGrandeWorro approved these changes

2024-06-03 22:21 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/vehicles/optionals/models/AlloyWheels.java
> +public class AlloyWheels {
Anche la classe andava rinominata non solo la tabella

2024-06-03 22:21 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/vehicles/optionals/enums/TypeOfRim.java
> +public enum TypeOfRim {
mettere l'of è un po' superfluo quando potrebbe essere chiamata RimsType

2024-06-07 00:20 UTC, ilGrandeWorro requested changes

2024-06-07 00:20 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/vehicles/optionals/models/Rims.java
> +        return price.setScale(2 , RoundingMode.HALF_EVEN);
setScale nel setter, non nel getter

2024-06-10 14:07 UTC, closed without merging