Create new order
develhope/Java23-Team2-Dealer pull request #47
Opened 2024-06-03 14:15 UTC by Calyen93

2024-06-03 15:59 UTC, alegudev39 approved these changes

2024-06-03 21:27 UTC, gabrielD4 requested changes

2024-06-03 21:27 UTC, gabrielD4 commented on src/test/java/com/develhope/spring/vehicles/services/OrderServiceTest.java
> +
test?

2024-06-03 21:31 UTC, Calyen93 commented on src/test/java/com/develhope/spring/vehicles/services/OrderServiceTest.java
> +
i test domani li vorrei fare con Lorenzo che ci sto provando e non ci riesco.

2024-06-03 22:13 UTC, gabrielD4 commented on src/test/java/com/develhope/spring/vehicles/services/OrderServiceTest.java
> +
ma hai provato su postman almeno e funziona?

2024-06-04 09:59 UTC, Calyen93 commented on src/test/java/com/develhope/spring/vehicles/services/OrderServiceTest.java
> +
su postman si

2024-06-04 11:40 UTC, ilGrandeWorro requested changes

2024-06-04 11:40 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/deals/dtos/OrderResponseDTO.java
> +
aggiungere ID dell'order,  quindi anche al costruttore, getter e setter

2024-06-04 11:40 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/deals/dtos/OrderStatusDTO.java
> +
Anche qui l'ID lo metterei

2024-06-04 11:40 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/deals/models/Order.java
> +    public Order(boolean downPayment, OrderStatus orderStatus, Vehicle vehicle) {
Non capisco il senso di questo costruttore

2024-06-04 11:40 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/deals/models/OrderMapper.java
> +        return new Order(
Questo lo rendi più chiaro creando un Order order = new Order (); e poi usando i setter per impostare i dati passando a parametro i corrispettivi getter del DTO

2024-06-04 11:40 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/users/dtos/UserCreatorDTO.java
> +=======
è rimasto questo

2024-06-04 11:40 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/users/dtos/UserCreatorDTO.java
Non ho capito che è successo, mi risultano tre UserCreatorDTO, uno cancellato e due coesistenti qui dentro

2024-06-04 11:40 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/users/models/User.java
> +    private void checkEmptyName(String name) throws EmptyParameterException {
Questa roba non dovrebbe essere fatta nell'entity, se proprio dobbiamo, spostiamola nel CreatorDTO

2024-06-04 11:40 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/users/models/UserMapper.java
> +    public static User toUser(UserCreatorDTO dto) throws EmptyParameterException, WrongEmailFormatException {
toUserFrom

2024-06-04 11:40 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/users/models/UserMapper.java
> +    public static UserCreatorDTO toUserCreatorDTO(User user) {
toUserCreatorDTOFrom

2024-06-05 08:44 UTC, gabrielD4 requested changes

2024-06-05 08:44 UTC, gabrielD4 commented on pom.xml
> +		<dependency>
come mai viene aggiunto lombok? che tra l'altro è gia presente?

2024-06-05 08:44 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/deals/models/OrderMapper.java
> +        Vehicle vehicle = new Vehicle();
Come disse Lorenzo megli ofarsi un costruttore con solo l id invece di usare set id. setId andrebbe rimosso

2024-06-05 08:44 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/deals/models/OrderMapper.java
> +        user.setId(orderCreatorDTO.getUserId());
idem

2024-06-05 08:44 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/deals/models/exceptions/OrderCreationException.java
> +public class OrderCreationException extends RuntimeException {
di cosa si occupa questa eccezione?

2024-06-05 08:44 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/exceptions/GlobalExceptionHandler.java
> +    @ExceptionHandler(VehicleNotFoundException.class)
questa non esiste più

2024-06-05 08:44 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/exceptions/GlobalExceptionHandler.java
> +    @ExceptionHandler(UserNotFoundException.class)
anceh questa non esiste più

2024-06-05 08:44 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/exceptions/GlobalExceptionHandler.java
> +    @ExceptionHandler(OrderCreationException.class)
non capisco questa eccezione di cosa si occupa

2024-06-05 08:44 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/exceptions/GlobalExceptionHandler.java
> +    @ExceptionHandler(EmptyParameterException.class)
questa anche non dovrebbe esistere

2024-06-05 08:44 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/exceptions/GlobalExceptionHandler.java
> +    @ExceptionHandler(WrongEmailFormatException.class)
anche questa non dovrebbe esserci

2024-06-05 08:44 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/users/models/User.java
> +    private void checkEmptyName(String name) throws EmptyParameterException {
questa roba non dovrebbbe starci più

2024-06-05 08:44 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/users/models/exceptions/EmptyParameterException.java
> +public class EmptyParameterException extends RuntimeException {
non dovrebbe esistere

2024-06-05 08:44 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/users/models/exceptions/WrongEmailFormatException.java
> +public class WrongEmailFormatException extends RuntimeException {
non dovrebbe esistere

2024-06-05 10:18 UTC, gabrielD4 approved these changes

2024-06-05 10:19 UTC, merged