Delete User
develhope/Java23-Team2-Dealer pull request #48
Opened 2024-06-03 17:15 UTC by ilGrandeWorro

Created delete method and added methods to check authorization and existence of the user you want to delete. Tested with postman

2024-06-07 09:49 UTC, gabrielD4 requested changes

2024-06-07 09:49 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/users/services/UserService.java
> +    private void checkIfUserExists(long userId){
non serve il repository già fa questo controllo

2024-06-07 09:49 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/users/services/UserService.java
> +        User userToDelete = userRepository.getReferenceById(userIDToDelete);
utilizza il findById con l'optional e spacchettalo con un elseThrow che è più sicuro.

2024-06-07 09:49 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/users/services/UserService.java
> +    }
testa

2024-06-11 10:04 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/users/services/UserService.java
> +    }
Croce. 
(no ok, mo lo faccio)

2024-06-11 15:16 UTC, Calyen93 approved these changes

2024-06-12 08:56 UTC, gabrielD4 requested changes

2024-06-12 08:56 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/users/services/UserService.java
> +    public void deleteUser (long userID, long userIDToDelete){
famolo generico per tutti per ora senza autorizzazione

2024-06-12 11:30 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/users/services/UserService.java
> +    public void deleteUser (long userID, long userIDToDelete){
Guarda che nella task UpdateOrder mi hai chiesto di inserire un controllo del ruolo. Io lo cancello, ma comincio a essere vagamente confuso (più del normale)

2024-06-14 15:45 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/users/services/UserService.java
> +    public void deleteUser (long userID, long userIDToDelete){
eh non so cosa io abbia detto, ma essendo che le cose cambiano potrebbe essere che abbia detto due volte una cosa giusta, come due volte una cazzataxD chissà

2024-06-14 15:48 UTC, gabrielD4 approved these changes

2024-06-14 15:48 UTC, merged