Endpoint return
develhope/Java23-Team2-Dealer pull request #50
Opened 2024-06-04 10:23 UTC by ilGrandeWorro

Ho modificato e creato i DTO di ritorno degli endpoint così che mostrino l'ID. Ne ho approfittato anche per rimuovere il builder di vehicle e fare delle correzioni su VehicleCreatorDTO che deteneva dei dati che sono fissi nell'entity, quindi inutili da settare

2024-06-04 20:23 UTC, gabrielD4 requested changes

2024-06-04 20:23 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/vehicles/models/VehicleMapper.java
> +    public VehicleCreatorDTO toCreatorDTOFrom(Vehicle vehicle) {
Cè incosistenza sul naming di questi metodi. A lorenzo non piace che si metta il "from" come ha fatto capire oggi in live. Perciò lasciamo solamente il "to" .

2024-06-04 20:28 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/vehicles/services/VehicleService.java
> +    public VehicleResponseDTO create(long userId, VehicleCreatorDTO vehicleCreatorDTO) {
Prova a farti un pull prima di pushare perchè questi metodi non dvrebbero essere così. :/

2024-06-05 09:18 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/vehicles/services/VehicleService.java
> +    public VehicleResponseDTO create(long userId, VehicleCreatorDTO vehicleCreatorDTO) {
Mi dice che è tutto aggiornato, forse stai guardando qualcosa che ancora non è stata mergiata

2024-06-07 09:04 UTC, gabrielD4 requested changes

2024-06-07 09:04 UTC, gabrielD4 commented on src/test/java/com/develhope/spring/vehicles/entities/VehicleTests.java
>  public class VehicleTests {
Fixa i conflitti, e rimetti in play manualmente i test uno per uno, non tutta la classe altrimenti non funzionano, e assicurati che passino di nuovo tutti dopo le modifiche, non voglio brutte più brutte sorpresexD

2024-06-08 09:05 UTC, gabrielD4 approved these changes

2024-06-08 09:05 UTC, gabrielD4 commented on src/test/java/com/develhope/spring/vehicles/entities/VehicleTests.java
>  public class VehicleTests {
comunque mi so sbagliato va messa in play tutta la classe, ma spero funzionassero comunque

2024-06-09 09:04 UTC, gabrielD4 approved these changes

2024-06-11 11:02 UTC, OigreSergio approved these changes

2024-06-11 11:03 UTC, merged

2024-06-11 11:04 UTC, Calyen93 approved these changes
Sono solo i DTO