deleteOrder Endpoint & Exception Handler
develhope/Java23-Team2-Dealer pull request #55
Opened 2024-06-07 10:16 UTC by Calyen93

2024-06-07 10:49 UTC, gabrielD4 requested changes

2024-06-07 10:49 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/deals/services/OrderService.java
> +        if (!orderRepository.existsById(orderId)) {
O catturi l'eccezione NoSuchElementException in u ntry catch e rilanci questa, oppure rimuovi questo controllo perchè già viene fatto dalla repository

2024-06-07 10:49 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/deals/dtos/DeleteOrderResponseDTO.java
> +    public DeleteOrderResponseDTO(String message) {
carino ci sta

2024-06-07 10:49 UTC, gabrielD4 commented on src/test/java/com/develhope/spring/deals/services/OrderServiceTest.java
> +
Anche i test con mockmvc

2024-06-07 12:52 UTC, Calyen93 commented
Già che mi trovavo ho creato anche il test per la creazione di un ordine che mancava e poi l'ho anche riutilizzato per cancellarlo

2024-06-07 14:46 UTC, gabrielD4 requested changes

2024-06-07 14:46 UTC, gabrielD4 commented on src/test/java/com/develhope/spring/deals/controllers/OrderControllerTest.java
> +@AutoConfigureMockMvc
aggiungi qua:
@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD)

2024-06-07 14:46 UTC, gabrielD4 commented on src/test/java/com/develhope/spring/deals/controllers/OrderControllerTest.java
> +                .andExpect(status().isCreated());
non mi basta l'errore devi anche controllare gli oggetti, vale per tutti i test anche scritti sotto, a meno che non lancino semplicemente un'eccezione e non ritornano nulla.

2024-06-07 14:46 UTC, gabrielD4 commented on src/test/java/com/develhope/spring/deals/services/OrderServiceTest.java
> +        doThrow(NoSuchElementException.class).when(orderRepository).deleteById(orderId);
Questa sintassi me la devi spiegare xD Non è ciò a cui sono abituato o abbiamo visto con lorenzo

2024-06-07 15:48 UTC, gabrielD4 requested changes

2024-06-07 15:48 UTC, gabrielD4 commented on src/test/java/com/develhope/spring/deals/services/OrderServiceTest.java
> +    }
fai anche i test di order mapper

2024-06-10 12:20 UTC, gabrielD4 requested changes

2024-06-10 12:20 UTC, gabrielD4 commented on src/test/java/com/develhope/spring/deals/controllers/OrderControllerTest.java
> +public class OrderControllerTest {
questi test sono alquanto confusi. Cè un misto di mockito e mvc, when mi pare sia un metodo solo di mockito che quindi non dovresti usare in un test con mock mvc

2024-06-10 12:20 UTC, gabrielD4 commented on src/test/java/com/develhope/spring/deals/services/OrderServiceTest.java
dove in questo test fai il setup dell'ambiente per il test? Per testare che delete funzioni, dovresti prima setuppare una repository dove viene salvato almeno un order

2024-06-11 12:07 UTC, gabrielD4 requested changes

2024-06-11 12:07 UTC, gabrielD4 commented on src/test/java/com/develhope/spring/deals/controllers/OrderControllerTest.java
> +        this.mockMvc.perform(delete("/v1/orders/{orderId}", 1)
pui scrivere così, ma se no puoi scrivere l'url come lo scirverti su postman

2024-06-11 12:07 UTC, gabrielD4 commented on src/test/java/com/develhope/spring/deals/controllers/OrderControllerTest.java
> +    void deleteOrder_ValidInput_ReturnsOk() throws Exception {
non capisco cosa ci sia di diverso dal test precedente

2024-06-11 12:07 UTC, gabrielD4 commented on src/test/java/com/develhope/spring/deals/controllers/OrderControllerTest.java
> +        doThrow(new OrderNotFoundException("Order with ID 1 not found", new NoSuchElementException()))
Questa se non erro è sintassi di mockito, non c'entra con integration test

2024-06-11 12:07 UTC, gabrielD4 commented on src/test/java/com/develhope/spring/deals/components/OrderMapperTest.java
> +import static org.mockito.Mockito.when;
mockito qua non ci deve stare

2024-06-11 12:07 UTC, gabrielD4 commented on src/test/java/com/develhope/spring/deals/services/OrderServiceTest.java
> +        assertEquals(DEFAULT_ORDER_RESPONSE_DTO.getVehicle().getId(), result.getVehicle().getId());
CI puo essere un solo assert per test, perciò scegliene uno,

2024-06-11 12:07 UTC, gabrielD4 commented on src/test/java/com/develhope/spring/deals/services/OrderServiceTest.java
> +        when(vehicleRepository.findById(DEFAULT_ORDER_CREATOR_DTO.getVehicleId()))
questo test è eccessivamente verboso per un delete e rnon comprendo la parte in cui richiami createOrder e anche dove gli dici doNothing quando la repository deve eliminare tramite id, visto che è ciò che dovrebbe fare

2024-06-11 12:07 UTC, gabrielD4 commented on src/test/java/com/develhope/spring/deals/services/OrderServiceTest.java
> +        when(userRepository.findById(DEFAULT_ORDER_CREATOR_DTO.getUserId()))
Uguale a sopra, troppo verboso. Tra l'altro non è necessario. Delete va sempre a buon fine anche se l 'id non esiste

2024-06-11 15:55 UTC, Calyen93 commented
I test funzionano tutti, giuro!

2024-06-12 02:20 UTC, ilGrandeWorro requested changes

2024-06-12 02:20 UTC, ilGrandeWorro commented on src/test/java/com/develhope/spring/deals/controllers/OrderControllerTest.java
Visto che il RentalControllerTest è stato rinominato in RentalIntegrationTest, direi che anche questo si può rinominare come OrderIntegrationTest

2024-06-12 02:20 UTC, ilGrandeWorro commented on src/test/java/com/develhope/spring/deals/controllers/OrderControllerTest.java
> +    private OrderController orderController;
Se ricordo bene, questo non dovrebbe proprio servire

2024-06-12 02:20 UTC, ilGrandeWorro commented on src/test/java/com/develhope/spring/deals/controllers/OrderControllerTest.java
> +                                """))
aggiungici un **.andExpect(status().isCreated())**
E aggiungici un **.andExpect(content().json("""{_OrderReturnDTO_}""")**

2024-06-13 10:46 UTC, gabrielD4 requested changes

2024-06-13 10:46 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/deals/controllers/OrderController.java
> +        return new DeleteOrderResponseDTO("Order deleted successfully");
va tolto non piace a Lorenzo

2024-06-13 10:46 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/deals/dtos/DeleteOrderResponseDTO.java
> +public class DeleteOrderResponseDTO {
non mi pareva una brutta idea, ma a lorenzo non piace

2024-06-13 10:46 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/deals/responseStatus/OrderNotFoundException.java
> +        this.httpStatus = HttpStatus.NOT_FOUND;
cambiala in bad request. Dovremmo farle un po con tutte, perchè not found come diceva oggi non fa capire il problema visto che si usa per le pagine non trovate

2024-06-13 10:46 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/deals/responseStatus/OrderNotFoundException.java
> +        super(message, ex);
non avevo visto questa cosa. Non la capisco perchè passi non sucheElementException. Nosuchelement la catturi e rilanci questa, ma non dovrebbero avere nulla a che vedere fra di loro

2024-06-13 10:46 UTC, gabrielD4 commented on src/test/java/com/develhope/spring/deals/components/OrderMapperTest.java
> +        assertEquals(expected.getVehicle().getId(), result.getVehicle().getId());
Non puoi avere tutti questi assert, solo uno per test

2024-06-13 10:46 UTC, gabrielD4 commented on src/test/java/com/develhope/spring/deals/components/OrderMapperTest.java
> +        assertEquals(true, result.isDownPayment());
stessa cosa

2024-06-14 14:13 UTC, closed without merging