Add references to user of orders and rentals, add consequential gette…
develhope/Java23-Team2-Dealer pull request #60
Opened 2024-06-09 16:44 UTC by gabrielD4

…r and setter and cuncstructor inizialization

2024-06-09 18:15 UTC, ilGrandeWorro requested changes
Credo che anche Vehicle abbia bisogno di essere bidirezionato

2024-06-09 19:05 UTC, gabrielD4 commented
> Credo che anche Vehicle abbia bisogno di essere bidirezionato

In questo caso non mi interessa quando cerco i veicoli vedere in che ordine stanno. Forse può valere per i noleggi, ma andrebbero prima divise le due repository per ciò.

2024-06-10 08:54 UTC, ilGrandeWorro approved these changes

2024-06-10 13:11 UTC, OigreSergio approved these changes

2024-06-10 13:12 UTC, OigreSergio requested changes
Risolvi i conflitti , per il resto il codice è ok

2024-06-11 10:16 UTC, gabrielD4 commented
Penso si possa eliminare questa pull reqeust a questo punto

2024-06-11 16:33 UTC, gabrielD4 commented
task portato a termine in #63

2024-06-11 16:33 UTC, closed without merging