changesMade
develhope/Java23-Team2-Dealer pull request #62
Opened 2024-06-10 14:06 UTC by OigreSergio

Alla fine non sono riuscito a riprendere il branch gia aperto , quindi ho copia incollato qui le cose ed ho sistemato i problemi che ci stavano col price , ditemi cosa ne pensate

2024-06-10 16:38 UTC, gabrielD4 approved these changes

2024-06-11 10:54 UTC, ilGrandeWorro requested changes

2024-06-11 10:54 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/vehicles/vehicleOptionals/models/Rims.java
> +public class Rims implements Optionals {
Manca la variabile di tipo RimType, ricordati poi di aggiunderla anche al costruttore e farci setter e getter

2024-06-11 15:44 UTC, Calyen93 approved these changes
Segna come risolti i conflitto in futuro, quello che è richiesto è stato comunque fatto!

2024-06-11 21:28 UTC, OigreSergio commented
AlloyWheels

2024-06-11 21:28 UTC, merged

2024-06-12 02:43 UTC, ilGrandeWorro commented on Java23-Team2-Dealer
Ma che è sta roba?

2024-06-12 02:46 UTC, ilGrandeWorro commented on Java23-Team2-Dealer
Che roba è?