New delete order
develhope/Java23-Team2-Dealer pull request #73
Opened 2024-06-14 12:13 UTC by Calyen93

2024-06-14 13:52 UTC, ilGrandeWorro requested changes

2024-06-14 13:52 UTC, ilGrandeWorro commented on src/test/java/com/develhope/spring/deals/controllers/OrderIntegrationTest.java
> +        this.mockMvc.perform(post("/v1/orders").contentType(MediaType.APPLICATION_JSON).content("""
Volendo c'è insertOrder() che puoi usare al posto di questa perform, anche perché non è stato inserito il controllo sicurezza in questa mock, quindi forse è qui che trovi l'incastro

2024-06-14 13:52 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/deals/controllers/OrderController.java
> +    @DeleteMapping("/{orderId}")
inserisci l'annotation Security

2024-06-14 13:52 UTC, ilGrandeWorro commented on src/test/java/com/develhope/spring/deals/controllers/OrderIntegrationTest.java
> +                .andExpect(status().isOk());
.andReturn();

2024-06-14 14:16 UTC, ilGrandeWorro approved these changes

2024-06-14 15:43 UTC, gabrielD4 requested changes

2024-06-14 15:43 UTC, gabrielD4 commented on src/test/java/com/develhope/spring/deals/controllers/OrderIntegrationTest.java
> +                        .with(httpBasic("hey@itsadmin.com", "1234")))
mh strano che passi autorizzazione ad un endpoint che non la richiede e funziona. Ma forse è normale così per mockmvc

2024-06-14 15:43 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/deals/services/OrderService.java
> +    public void delete(Long orderId) {
Io seguirei quello che ha detto lorenzo così poi non ci dobbiamo piu pensare.

2024-06-14 15:43 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/deals/controllers/OrderController.java
> +    public void deleteOrder(@PathVariable Long orderId) {
farei come dice lorenzo e non ci penserei più, altrimenti scegli almeno uno dei due tipi di accesso e poi ci pensiamo, ma non lasciare questo end point libero

2024-06-16 15:24 UTC, gabrielD4 requested changes

2024-06-16 15:24 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/deals/controllers/OrderController.java
> +    @DeleteMapping("/{orderId}")
Mi sa che dobbiamo vederla un attimo assieme la cosa perchè non è esattamente così che dovrebbe essere. Mi dispiace capo

2024-06-21 10:17 UTC, alegudev39 approved these changes

2024-06-21 12:46 UTC, gabrielD4 approved these changes

2024-06-21 12:46 UTC, merged