New refs
develhope/Java23-Team2-Dealer pull request #74
Opened 2024-06-17 09:40 UTC by ilGrandeWorro

2024-06-17 12:43 UTC, alegudev39 commented on src/main/java/com/develhope/spring/deals/dtos/OrderCreatorDTO.java
> +                           boolean paid, List<User> sellers) {
come mai hai deciso di passare la lista di sellers e non l'ID del seller?

2024-06-17 12:50 UTC, alegudev39 approved these changes

2024-06-19 08:48 UTC, OigreSergio approved these changes

2024-06-21 11:11 UTC, gabrielD4 requested changes

2024-06-21 11:11 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/deals/dtos/OrderResponseDTO.java
>  public class OrderResponseDTO {
e allora chiamalo OrderSavedDTO, come anche l'altro, se no così non si capisce

2024-06-21 11:11 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/deals/dtos/OrderReworkedDTO.java
> +    public OrderReworkedDTO(Long id, boolean downPayment, OrderStatus orderStatus, boolean paid) {
Questo a sto punto chiamiamolo OrderUpdatedDto e così anche l'altro

2024-06-21 11:11 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/deals/dtos/OrderCreatorDTO.java
> +    private List<User> sellers;
Non è una lista, è un venditore unico o un admin unico. Uguale per tutti i DTO che vedo hai inserito la stessa cosa

2024-06-21 11:11 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/deals/dtos/OrderCreatorDTO.java
> +                           boolean paid, List<User> sellers) {
hai fatto una domanda corretta, perchè hai messo l'approve però allora?

2024-06-21 11:11 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/deals/models/Order.java
> +    private List<User> sellers;
qui naturalmente ci va un singolo user aggiunto ed uguale nell'altro

2024-06-21 11:11 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/users/components/UserMapper.java
> -        return new UserSavedDTO(user.getId(), user.getName(), user.getSurname(), user.getUsername(),user.getRoles());
non capisco tutte ste righe eliminate che non ricompaiono

2024-06-21 11:11 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/users/dtos/UserResponseDTO.java
> +    public UserResponseDTO(long id, String name, String surname, String userName, Roles roles) {
ah allora era UserSavedDto come doveva correttamente essere. Questa pull request ha una marea di cambi che non erano necessari o richiesti al fine del task

2024-06-21 11:11 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/users/models/User.java
> +    private Order soldOrder;
no questo non ci dovrebbe essere

2024-06-21 11:11 UTC, gabrielD4 commented on src/main/java/com/develhope/spring/users/models/User.java
> +    private Rental soldRental;
non ci dovrebbe essere cè gia la reference agli ordini esattamente sopra

2024-06-21 11:12 UTC, gabrielD4 commented
In generale troppe modifiche a cosa non necessarie o richieste come avevamo stabilito di evitare di fare. Comunque poi ricontrolla che tutto funzioni

2024-06-21 11:52 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/deals/dtos/OrderReworkedDTO.java
> +    public OrderReworkedDTO(Long id, boolean downPayment, OrderStatus orderStatus, boolean paid) {
Updated si confonde con Updater

2024-06-21 11:57 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/deals/dtos/OrderCreatorDTO.java
> +    private List<User> sellers;
Sì, l'ho elaborata male concettualmente, la correggo subito

2024-06-21 12:02 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/users/components/UserMapper.java
> -        return new UserSavedDTO(user.getId(), user.getName(), user.getSurname(), user.getUsername(),user.getRoles());
Sarebbe il toResponseDTO

2024-06-21 12:02 UTC, ilGrandeWorro commented on src/main/java/com/develhope/spring/users/components/UserMapper.java
> -        return new UserSavedDTO(user.getId(), user.getName(), user.getSurname(), user.getUsername(),user.getRoles());
Sarebbe il toResponseDTO, ma tanto rinomino tutti i Response come Saved

2024-06-22 10:15 UTC, closed without merging