Problema risolto, bastava riscriverlo da capo
develhope/Java23-Team2-Dealer pull request #76
Opened 2024-06-21 17:49 UTC by ilGrandeWorro

2024-06-22 09:47 UTC, gabrielD4 requested changes

2024-06-22 09:47 UTC, gabrielD4 commented on src/test/java/com/develhope/spring/deals/services/OrderServiceTest.java
> +    private OrderMapper orderMapper;
non va iniettato il mapper, va iniettata la classe che si testa

2024-06-22 10:20 UTC, ilGrandeWorro commented on src/test/java/com/develhope/spring/deals/services/OrderServiceTest.java
> +    private OrderMapper orderMapper;
Non l'ho iniettato io, l'ho preso dal main

2024-06-22 10:20 UTC, ilGrandeWorro commented on src/test/java/com/develhope/spring/deals/services/OrderServiceTest.java
> +    private OrderMapper orderMapper;
Non l'ho iniettato io, l'ho preso dal main.

2024-06-26 15:11 UTC, gabrielD4 approved these changes

2024-06-26 15:11 UTC, merged